customhost = "database-1.covmrntvvl5a.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leejiapoh-employee"
customregion = "us-east-1"
